POST http://localhost:8080/api/v1/connect
Content-Type: application/json

{
  "macAddress": "24:62:ab:b7:c2:50",
  "serialNumber": "N/A"
}

> {% client.global.set("controller_jwt", response.body.trim()) %}

###

GET http://localhost:8080/api/v1/controllers/me
Accept-Type: application/json
Authorization: Bearer {{controller_jwt}}

###

GET http://localhost:8080/api/v1/controllers/action
Accept-Type: application/json
Authorization: Bearer {{controller_jwt}}

###

POST http://localhost:8080/api/v1/controllers/record
Content-Type: application/json
Authorization: Bearer {{controller_jwt}}

{
  "ambientTemperature": 24.100000,
  "ambientHumidity": 42.500000,
  "soilMoisture": 873
}
