POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "brian@bnorm.com",
  "password": "vegard"
}

> {% client.global.set("user_jwt", response.body.trim()) %}

###

GET http://localhost:8080/api/v1/users
Accept-Type: application/json
Authorization: Bearer {{user_jwt}}

###

GET http://localhost:8080/api/v1/users/me
Accept-Type: application/json
Authorization: Bearer {{user_jwt}}

###

GET http://localhost:8080/api/v1/controllers
Accept-Type: application/json
Authorization: Bearer {{user_jwt}}

###

GET http://localhost:8080/api/v1/controllers/1
Accept-Type: application/json
Authorization: Bearer {{user_jwt}}

###

GET http://localhost:8080/api/v1/controllers/1/records?startTime=2020-07-04T00:00:00Z&endTime=2020-07-05T00:00:00Z
Accept-Type: application/json
Authorization: Bearer {{user_jwt}}
